version: "3.7"

services:

  #front_end:
    #build: ./Front-End
    #ports:
      #- 5000:80

  messaging:
    image: rabbitmq:3.8.2-management
    hostname: messaging
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
  cluster1:
    image: rabbitmq:3.8.2-management
    hostname: cluster1
    depends_on:
      - messaging
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=messaging
      - RAM_NODE=true
  cluster2:
    image: rabbitmq:3.8.2-management
    hostname: cluster2
    depends_on:
      - messaging
      - cluster1
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=messaging

  back_end:
    build: ./Back-End
    depends_on:
      - database
      - messaging
    volumes:
     - "./Back-End:/usr/src/myapp"
  database:
    build: ./Database-1
    volumes:
      - "./Database-1/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
