version: "3.7"

services:

  front_end:
    build: ./Front-End # Needs editing
    ports:
      - 5000:80

  messaging:
    image: rabbitmq:3.8.2-management-alpine
    #build: ./Messaging Dockerfile needs to be created in this folder
    ports:
      - 5672:5672 # Default port for RabbitMQ message broker
      - 15672:15672 # Default port for RabbitMQ GUI

  back_end:
    build: ./Back-End
    depends_on:
      - messaging
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'

  database:
    build: ./Database-1
    volumes:
      - "./Database-1/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
