# Author: Freddy Roa-Familia
# Version: 1.1
version: '3'
services:
 front_end:
  build: /Users/freddy/Documents/NJIT/Spring 2020/IT-490/Group_Project/Front-End # Needs editing
  ports: 
   - 80:80
 messaging:
  image: 'rabbitmq:3.8.2-management-alpine'
  ports:
   - 5672:5672   # Default port for RabbitMQ message broker
   - 15672:15672 # Default port for RabbitMQ GUI
 #mariadb: 
  #image: 'mariadb'
  #environment:
   #MYSQL_ROOT_PASSWORD: secret-pw
   # Sets the default password 